project:
  type: website
  render:
    - index.qmd
    - opendata.qmd
    - script.qmd
    - 30daymapchallenge.qmd
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true

website:
  title: "SHED"
  navbar:
    left:
      - href: index.qmd
        text: "index"
      - href: opendata.qmd
        text: "open data"
      - href: script.qmd
        text: "python script"
      - href: 30daymapchallenge.qmd
        text: "30 day maps"        
  site-url: "https://anisotropi4@anisotropi4.github.io/shed/" # makes site links work on your remote site

execute:
  freeze: auto
